# Generated by Django 5.0.3 on 2024-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tfa_secret",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
